#!/bin/sh
lint_output=$(yarn lint --quiet)
lint_exit_code=$?

echo "$lint_output"  # Output the lint result

if [ $lint_exit_code -ne 0 ]; then
  echo "Lint errors or warnings found. Commit aborted."
  exit 1
fi
