#!/bin/sh
lint_output=$(yarn lint)
lint_exit_code=$?

echo "$lint_output"  # Output the lint result

if [ $lint_exit_code -ne 0 ]; then
  echo "Lint errors found. Commit aborted."
  exit 1
fi

warning_count=$(echo "$lint_output" | grep -i "warning:" | wc -l | xargs)
if [ $warning_count -ne 0 ]; then
  echo "Lint warnings found. Commit aborted."
  exit 1
fi
